name: Build and Package Ragabology App

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Build and Package App with Electron Forge
      run: npm run make

    # Assuming npm run make configures Electron Forge to create a macOS package.
    # You might need to adjust this if you have a specific script for .pkg packaging.
    # This could involve a custom Electron Forge maker configuration or an external tool.

    - name: Locate and Upload .pkg Artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: Ragabology-pkg
        # Update the path according to where your .pkg file is actually saved.
        path: out/make/**/*.pkg
