name: Electron Build for macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install npm dependencies
      run: npm install

    - name: Package Electron app for macOS
      run: npx electron-packager . ragabology --overwrite --platform=darwin --arch=arm64 --out=out --prune=true

    - name: Create .pkg installer
      run: |
        pkgbuild --root out/ragabology-darwin-arm64/ragabology.app \
                 --identifier com.tqbox.ragabology \
                 --version "1.0.0" \
                 --install-location /Applications/ragabology.app \
                 out/ragabology-1.0.0.pkg

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ragabology-builds
        path: out/
